spring.jpa.hibernate.ddl-auto: update
spring.jpa.database: POSTGRESQL
spring.datasource.url: YOUR_DATASOURCE
spring.datasource.username : YOUR_DATASOURCE_USERNAME
spring.datasource.password : YOUR_DATASOURCE_PASSWORD


addon:
  key: jira-twilio-notif
  base-url: https://c98e7086.ngrok.io

logging.level.com.atlassian.connect.spring: DEBUG

twilio.account.sid : YOUR_TWILIO_ACCOUNT_SID
twilio.auth.token : YOUR_TWILIO_AUTH_TOKEN
twilio.phonenumber : YOUR_TWILIO_PHONE_NUMBER

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet.content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    # prefix: /templates/
    # suffix: .html
    # template-resolver-order:
    # view-names: