spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL

addon:
  key: jira-twilio-notif
  base-url: https://c98e7086.ngrok.io

logging.level.com.atlassian.connect.spring: DEBUG

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet.content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    # prefix: /templates/
    # suffix: .html
    # template-resolver-order:
    # view-names:
