spring.jpa.hibernate.ddl-auto: update
spring.jpa.database: POSTGRESQL
spring.datasource.username : postgres
spring.datasource.password : root
spring.datasource.url: jdbc:postgresql://localhost:5432/jira-twilio-db

addon:
  key: jira-twilio-notif
  base-url: https://c98e7086.ngrok.io

logging.level.com.atlassian.connect.spring: DEBUG

twilio.baseurl : https://verify.twilio.com/v2/
twilio.account.sid : ACcb09fcc16f065dbc190db28f39a7094b
twilio.auth.token : ENTER-YOUR-TWILIO-AUTH-TOKEN

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet.content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    # prefix: /templates/
    # suffix: .html
    # template-resolver-order:
    # view-names: